apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
        - name: web-server
          image: lauraleonilla/express-web-server:latest
          env:
          - name: PORT
            value: "8080"